INSERT INTO finding_class_catalogue (finding_class,finding_category,description,enabled) VALUES
('cve','vulnerability','Cve',TRUE),
('package_vulnerability','vulnerability','Package vulnerability',TRUE),
('kernel_vulnerability','vulnerability','Kernel vulnerability',TRUE),
('unsupported_software','vulnerability','Unsupported software',TRUE),
('missing_security_update','vulnerability','Missing security update',TRUE),
('network_service_vulnerability','vulnerability','Network service vulnerability',TRUE),
('network_service_exposure','vulnerability','Network service exposure',TRUE),
('weak_cryptography','vulnerability','Weak cryptography',TRUE),
('insecure_protocol','vulnerability','Insecure protocol',TRUE),
('service_misconfiguration','vulnerability','Service misconfiguration',TRUE),
('default_credentials','vulnerability','Default credentials',TRUE),
('authentication_weakness','vulnerability','Authentication weakness',TRUE),
('certificate_issue','vulnerability','Certificate issue',TRUE),
('cis_control','compliance_drift','Cis control',TRUE),
('lynis_hardening','compliance_drift','Lynis hardening',TRUE),
('security_configuration','compliance_drift','Security configuration',TRUE),
('service_configuration','compliance_drift','Service configuration',TRUE),
('authentication_configuration','compliance_drift','Authentication configuration',TRUE),
('access_control_configuration','compliance_drift','Access control configuration',TRUE),
('logging_configuration','compliance_drift','Logging configuration',TRUE),
('filesystem_configuration','compliance_drift','Filesystem configuration',TRUE),
('network_configuration','compliance_drift','Network configuration',TRUE),
('web_application_vulnerability','vulnerability','Web application vulnerability',TRUE),
('web_misconfiguration','vulnerability','Web misconfiguration',TRUE),
('exposed_sensitive_information','vulnerability','Exposed sensitive information',TRUE),
('exposed_service','vulnerability','Exposed service',TRUE),
('security_header_missing','vulnerability','Security header missing',TRUE),
('tls_configuration','vulnerability','Tls configuration',TRUE),
('injection_vulnerability','vulnerability','Injection vulnerability',TRUE),
('xss_vulnerability','vulnerability','Xss vulnerability',TRUE),
('ssrf_vulnerability','vulnerability','Ssrf vulnerability',TRUE),
('path_traversal','vulnerability','Path traversal',TRUE),
('file_exposure','vulnerability','File exposure',TRUE),
('misconfigured_cloud_service','vulnerability','Misconfigured cloud service',TRUE),
('container_image_vulnerability','vulnerability','Container image vulnerability',TRUE),
('container_dependency_vulnerability','vulnerability','Container dependency vulnerability',TRUE),
('container_misconfiguration','compliance_drift','Container misconfiguration',TRUE),
('container_secret_exposure','vulnerability','Container secret exposure',TRUE),
('container_license_issue','vulnerability','Container license issue',TRUE),
('dockerfile_misconfiguration','compliance_drift','Dockerfile misconfiguration',TRUE),
('iac_misconfiguration','compliance_drift','Iac misconfiguration',TRUE),
('file_integrity_change','integrity_drift','File integrity change',TRUE),
('rootkit_detection','rootkit','Rootkit detection',TRUE)
ON CONFLICT (finding_class) DO UPDATE SET finding_category=EXCLUDED.finding_category,description=EXCLUDED.description,enabled=EXCLUDED.enabled,updated_at=now();
